# Generated by Django 3.0.3 on 2020-04-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a text description Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium cumque delectus dolore excepturi fugit ipsa magni necessitatibus reiciendis vel veniam.'),
            preserve_default=False,
        ),
    ]
